### ISSUE TITLE
Player does not receive chatReceive via private rooms.

### ISSUE THREAD

**Issue by mcapu** [TF2Stadium/Helen#117]
This creates an issue in which the lobby chat will not update if the user is in another page.

**Comment by vibhavp** [comment]
Sending messages over the public and private rooms will cause them to be duplicated on the frontend.

**Comment by mcapu** [comment]
Currently, the frontend supports editing messages with the same id, so as long as the chatReceive `id` field is the same, they won't get duplicated.

**Comment by vibhavp** [comment]
fixed in 94f6b983f73865106e447098b7b41201ab5c1b9c
