### ISSUE TITLE
lobbyData does not contain envelop

### ISSUE THREAD

**Issue by DSchalla** [TF2Stadium/Helen#36]
When being a player in a lobby and receiving its updates, the message sent by the server does not contain a envelop/event name?

WebSocket extract:
```
42["lobbyListData","{\"lobbies\":[{\"classes\":{\"demoman\":{\"blu\"[...]
```
LobbyData:
```
42["{\"classes\":{\"demoman\":{\"blu\":{\"name\":\[...]
```

**Comment by vibhavp** [comment]
Fixed in d0e7553b775f0a52fe023944b0c1186e1c550ca4
