### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by vibhavp** [TF2Stadium/Helen#69]
* When someone reconnect, make them join the public AND private rooms of the lobby they're PLAYING.

* On `lobbyJoin`, make them join the PRIVATE ROOM, on lobbySpectatorJoin, make them join the PUBLIC ROOM

* When someone disconnects, we get the Steam ID from their socket ID, then check if there are multiple connected sockets for that SteamID. *If there no more sockets left* (no tabs): We remove them from the spectator of the lobby they were spectating. If there are sockets left*, we check if these sockets are spectating the same lobbies the previous socket was. If no, the player is removed the from the spectator slot of these lobbies.

**Comment by mcapu** [comment]
I want to add to this that the Private Rooms should only send `lobbyReadyUp` and `lobbyStart`. The other requests, like `lobbyData`, should be sent by the Public Rooms.
